# Generated by Django 3.2 on 2020-07-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200709_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lure',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
